export const FETCH_DATA_START = 'FETCH_DATA_START',
  FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS',
  FETCH_DATA_FAILURE = 'FETCH_DATA_FAILURE',
  FETCH_DATA_END = 'FETCH_DATA_END',

  SET_STATE = 'SET_STATE',
  LOGIN = 'LOGIN',
  LOGOUT = 'LOGOUT',

  ACTIVE_TAB = 'ACTIVE_TAB',
  SET_POPUP = 'SET_POPUP',
  POPUP_MESSAGE = 'POPUP_MESSAGE',

  ALBUMS = 'ALBUMS',
  SELECT_ALBUM = 'SELECT_ALBUM',

  USER_CHANNELS = 'USER_CHANNELS',
  USERS = 'USERS',
  DISABLED_USER_CHANNELS = 'DISABLED_USER_CHANNELS',
  AVAILABLE_CHANNELS = 'AVAILABLE_CHANNELS',
  PURCHASED_CHANNELS = 'PURCHASED_CHANNELS',
  FOUND_CHANNELS = 'FOUND_CHANNELS',
  BROADCAST = 'BROADCAST',
  CHANNEL_STATE = 'CHANNEL_STATE',

  TARIFF = 'TARIFF',
  BALANCE = 'BALANCE',
  HISTORY = 'HISTORY',

  REFERRALS = 'REFERRALS',

  SOLD_STREAMS = 'SOLD_STREAMS',
  PURCHASED_STREAMS = 'PURCHASED_STREAMS',

  VIDEOS = 'VIDEOS',
  SELECT_VIDEO = 'SELECT_VIDEO',
  SELECT_VIDEOS = 'SELECT_VIDEOS',
  EDIT_VIDEO = 'EDIT_VIDEO',

  START = 'START',
  CLEAR_STATUS = 'CLEAR_STATUS',
  SUCCESS = 'SUCCESS',
  FAILURE = 'FAILURE',
  POPUP_SUCCESS = 'POPUP_SUCCESS',
  POPUP_FAILURE = 'POPUP_FAILURE',

  IS_MOBILE = 'IS_MOBILE';
